// <auto-generated />
using System;
using FastFoodAPI.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FastFoodAPI.Migrations
{
    [DbContext(typeof(FastFoodDbContext))]
    [Migration("20250413172843_FixEmployee")]
    partial class FixEmployee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FastFoodAPI.Entities.Employee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobTitleId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StationId")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("JobTitleId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("StationId");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3052ecc5-6773-49e4-94f6-8303318375fe",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fb71e81f-2b0b-4f68-ac3f-a33ed965eec4",
                            Email = "john.doe@onlybytes.com",
                            EmailConfirmed = false,
                            FirstName = "John",
                            JobTitleId = 1,
                            LastName = "Doe",
                            LockoutEnabled = false,
                            NormalizedEmail = "JOHN.DOE@ONLYBYTES.COM",
                            NormalizedUserName = "JOHN.DOE@ONLYBYTES.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "215d07dc-e3b8-411f-bd44-27567c4a4cec",
                            StationId = 1,
                            TwoFactorEnabled = false,
                            UserName = "john.doe@onlybytes.com"
                        },
                        new
                        {
                            Id = "07c4d294-fd34-4882-83c1-4e2ac1be48f7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2f5732e4-6f48-401a-9821-4380d862c32f",
                            Email = "sarah.johnson@onlybytes.com",
                            EmailConfirmed = false,
                            FirstName = "Sarah",
                            JobTitleId = 1,
                            LastName = "Johnson",
                            LockoutEnabled = false,
                            NormalizedEmail = "SARAH.JOHNSON@ONLYBYTES.COM",
                            NormalizedUserName = "SARAH.JOHNSON@ONLYBYTES.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c6e66793-e3d8-4a10-910e-80b2807b6106",
                            StationId = 1,
                            TwoFactorEnabled = false,
                            UserName = "sarah.johnson@onlybytes.com"
                        },
                        new
                        {
                            Id = "ffc8c095-b46d-43d1-9976-9ea42f4a171d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fa18a3e5-fe4a-41b2-875f-df7365584e5f",
                            Email = "richard.parker@onlybytes.com",
                            EmailConfirmed = false,
                            FirstName = "Richard",
                            JobTitleId = 1,
                            LastName = "Parker",
                            LockoutEnabled = false,
                            NormalizedEmail = "RICHARD.PARKER@ONLYBYTES.COM",
                            NormalizedUserName = "RICHARD.PARKER@ONLYBYTES.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "dc3e2758-6fa1-4768-a369-9bd0ab7875f1",
                            StationId = 1,
                            TwoFactorEnabled = false,
                            UserName = "richard.parker@onlybytes.com"
                        },
                        new
                        {
                            Id = "d8be7bf6-f6ad-4835-8408-0ee470aef7a8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "75cc3512-33ad-45e0-936f-51bbddd71af1",
                            Email = "amanda.williams@onlybytes.com",
                            EmailConfirmed = false,
                            FirstName = "Amanda",
                            JobTitleId = 1,
                            LastName = "Williams",
                            LockoutEnabled = false,
                            NormalizedEmail = "AMANDA.WILLIAMS@ONLYBYTES.COM",
                            NormalizedUserName = "AMANDA.WILLIAMS@ONLYBYTES.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8099b455-8830-4685-941c-aad93c47401f",
                            StationId = 1,
                            TwoFactorEnabled = false,
                            UserName = "amanda.williams@onlybytes.com"
                        },
                        new
                        {
                            Id = "b27ce3ff-1b76-4c28-9368-74cee1b1c104",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e09a7b63-85f3-4808-a961-985bd9e0f632",
                            Email = "jane.smith@onlybytes.com",
                            EmailConfirmed = false,
                            FirstName = "Jane",
                            JobTitleId = 2,
                            LastName = "Smith",
                            LockoutEnabled = false,
                            NormalizedEmail = "JANE.SMITH@ONLYBYTES.COM",
                            NormalizedUserName = "JANE.SMITH@ONLYBYTES.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "255e30c3-8d50-4fc6-97d7-e7c5c894b270",
                            StationId = 2,
                            TwoFactorEnabled = false,
                            UserName = "jane.smith@onlybytes.com"
                        },
                        new
                        {
                            Id = "ac8baf0a-aeb8-40c5-a8b4-632c5f692b70",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "562ce9ba-5f51-45b2-a523-55f2cf1cc514",
                            Email = "michael.brown@onlybytes.com",
                            EmailConfirmed = false,
                            FirstName = "Michael",
                            JobTitleId = 2,
                            LastName = "Brown",
                            LockoutEnabled = false,
                            NormalizedEmail = "MICHAEL.BROWN@ONLYBYTES.COM",
                            NormalizedUserName = "MICHAEL.BROWN@ONLYBYTES.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e855fc78-c49a-4a40-9f7f-fc9454daa37c",
                            StationId = 3,
                            TwoFactorEnabled = false,
                            UserName = "michael.brown@onlybytes.com"
                        },
                        new
                        {
                            Id = "de06c55e-1814-486a-805e-72a0d925cc13",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b6beaf2b-8f2d-4a01-bccb-1df51d71cfb7",
                            Email = "emily.davis@onlybytes.com",
                            EmailConfirmed = false,
                            FirstName = "Emily",
                            JobTitleId = 2,
                            LastName = "Davis",
                            LockoutEnabled = false,
                            NormalizedEmail = "EMILY.DAVIS@ONLYBYTES.COM",
                            NormalizedUserName = "EMILY.DAVIS@ONLYBYTES.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "362e5e8f-fc1e-4b6b-b789-ea286fcc0a6f",
                            StationId = 2,
                            TwoFactorEnabled = false,
                            UserName = "emily.davis@onlybytes.com"
                        },
                        new
                        {
                            Id = "8efb3ddf-77b9-4f66-a6c5-08e3d0e1a4fb",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "32b1db7e-4ea9-4f9b-88a8-114504b1c055",
                            Email = "daniel.thompson@onlybytes.com",
                            EmailConfirmed = false,
                            FirstName = "Daniel",
                            JobTitleId = 2,
                            LastName = "Thompson",
                            LockoutEnabled = false,
                            NormalizedEmail = "DANIEL.THOMPSON@ONLYBYTES.COM",
                            NormalizedUserName = "DANIEL.THOMPSON@ONLYBYTES.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fe5f7a34-568b-43d3-a693-752f10566a0b",
                            StationId = 3,
                            TwoFactorEnabled = false,
                            UserName = "daniel.thompson@onlybytes.com"
                        },
                        new
                        {
                            Id = "87dd16c6-7fe5-43e2-a378-8de5b3c8aff9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "379cc76e-d222-4613-9a0e-1900420fd0ad",
                            Email = "olivia.rodriguez@onlybytes.com",
                            EmailConfirmed = false,
                            FirstName = "Olivia",
                            JobTitleId = 2,
                            LastName = "Rodriguez",
                            LockoutEnabled = false,
                            NormalizedEmail = "OLIVIA.RODRIGUEZ@ONLYBYTES.COM",
                            NormalizedUserName = "OLIVIA.RODRIGUEZ@ONLYBYTES.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "531c0ca6-b393-4875-9014-2588dfd0e520",
                            StationId = 2,
                            TwoFactorEnabled = false,
                            UserName = "olivia.rodriguez@onlybytes.com"
                        },
                        new
                        {
                            Id = "6139a95f-6ef3-4160-9cc2-45914eb759a6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1e46073b-c928-4f2c-8d65-d7880bc8bf24",
                            Email = "thomas.lee@onlybytes.com",
                            EmailConfirmed = false,
                            FirstName = "Thomas",
                            JobTitleId = 2,
                            LastName = "Lee",
                            LockoutEnabled = false,
                            NormalizedEmail = "THOMAS.LEE@ONLYBYTES.COM",
                            NormalizedUserName = "THOMAS.LEE@ONLYBYTES.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "29931e57-3cfe-4304-8e90-1e4c00c85282",
                            StationId = 3,
                            TwoFactorEnabled = false,
                            UserName = "thomas.lee@onlybytes.com"
                        },
                        new
                        {
                            Id = "6cd3cd47-9274-4f6d-ac00-54e6dab140f5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "18c85f65-8d84-4b5b-8bcd-17e55974de83",
                            Email = "sophia.patel@onlybytes.com",
                            EmailConfirmed = false,
                            FirstName = "Sophia",
                            JobTitleId = 2,
                            LastName = "Patel",
                            LockoutEnabled = false,
                            NormalizedEmail = "SOPHIA.PATEL@ONLYBYTES.COM",
                            NormalizedUserName = "SOPHIA.PATEL@ONLYBYTES.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "27bc350f-8ebd-4307-a9af-81133974f89b",
                            StationId = 2,
                            TwoFactorEnabled = false,
                            UserName = "sophia.patel@onlybytes.com"
                        },
                        new
                        {
                            Id = "41893200-b954-40f2-9ab8-fd11ecf243b0",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ba48a4ee-680e-4350-914a-3fd955bc4206",
                            Email = "mike.wilson@onlybytes.com",
                            EmailConfirmed = false,
                            FirstName = "Mike",
                            JobTitleId = 3,
                            LastName = "Wilson",
                            LockoutEnabled = false,
                            NormalizedEmail = "MIKE.WILSON@ONLYBYTES.COM",
                            NormalizedUserName = "MIKE.WILSON@ONLYBYTES.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c44475e6-c58e-4b8c-ba5a-2b8ad5303ea9",
                            StationId = 4,
                            TwoFactorEnabled = false,
                            UserName = "mike.wilson@onlybytes.com"
                        },
                        new
                        {
                            Id = "fc124823-5743-41fd-aded-24a88ef1e44c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "562101c4-6a05-470b-8913-5a30fad981cf",
                            Email = "david.garcia@onlybytes.com",
                            EmailConfirmed = false,
                            FirstName = "David",
                            JobTitleId = 3,
                            LastName = "Garcia",
                            LockoutEnabled = false,
                            NormalizedEmail = "DAVID.GARCIA@ONLYBYTES.COM",
                            NormalizedUserName = "DAVID.GARCIA@ONLYBYTES.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "053b5ce0-fb39-4c8d-967c-ff1b9e949eca",
                            StationId = 5,
                            TwoFactorEnabled = false,
                            UserName = "david.garcia@onlybytes.com"
                        },
                        new
                        {
                            Id = "c34a7241-df42-4185-bee7-f5d1e329218c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d12d25c2-24ff-470b-ad29-ca40cb583b48",
                            Email = "jessica.martinez@onlybytes.com",
                            EmailConfirmed = false,
                            FirstName = "Jessica",
                            JobTitleId = 3,
                            LastName = "Martinez",
                            LockoutEnabled = false,
                            NormalizedEmail = "JESSICA.MARTINEZ@ONLYBYTES.COM",
                            NormalizedUserName = "JESSICA.MARTINEZ@ONLYBYTES.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "df0061e8-aadf-4f28-83de-b9b98aef1387",
                            StationId = 6,
                            TwoFactorEnabled = false,
                            UserName = "jessica.martinez@onlybytes.com"
                        },
                        new
                        {
                            Id = "05d17d04-3c61-4d1c-8e52-f6cc7c3bf9bf",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "da2aaa5d-74c6-4649-be66-001b2be88e61",
                            Email = "james.wilson@onlybytes.com",
                            EmailConfirmed = false,
                            FirstName = "James",
                            JobTitleId = 3,
                            LastName = "Wilson",
                            LockoutEnabled = false,
                            NormalizedEmail = "JAMES.WILSON@ONLYBYTES.COM",
                            NormalizedUserName = "JAMES.WILSON@ONLYBYTES.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "84748a36-5909-4654-b304-9ffba67ff093",
                            StationId = 4,
                            TwoFactorEnabled = false,
                            UserName = "james.wilson@onlybytes.com"
                        },
                        new
                        {
                            Id = "11cc7b1a-09ba-48b6-a062-1b84769ed181",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "34106604-6da0-41a5-b208-fcf044174cf8",
                            Email = "maria.hernandez@onlybytes.com",
                            EmailConfirmed = false,
                            FirstName = "Maria",
                            JobTitleId = 3,
                            LastName = "Hernandez",
                            LockoutEnabled = false,
                            NormalizedEmail = "MARIA.HERNANDEZ@ONLYBYTES.COM",
                            NormalizedUserName = "MARIA.HERNANDEZ@ONLYBYTES.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5805eeba-fc1c-4a79-b979-870ca509be2c",
                            StationId = 5,
                            TwoFactorEnabled = false,
                            UserName = "maria.hernandez@onlybytes.com"
                        },
                        new
                        {
                            Id = "3a4088e6-f9f2-459a-91f3-d86d52d6ba16",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3cc29c83-a3d8-4e77-bade-577a58cdefeb",
                            Email = "kevin.kim@onlybytes.com",
                            EmailConfirmed = false,
                            FirstName = "Kevin",
                            JobTitleId = 3,
                            LastName = "Kim",
                            LockoutEnabled = false,
                            NormalizedEmail = "KEVIN.KIM@ONLYBYTES.COM",
                            NormalizedUserName = "KEVIN.KIM@ONLYBYTES.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b8937ed6-aa20-48f3-b1aa-2358b906c3ea",
                            StationId = 6,
                            TwoFactorEnabled = false,
                            UserName = "kevin.kim@onlybytes.com"
                        },
                        new
                        {
                            Id = "d8838fca-fee1-4a1c-b320-95262db7cd9a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "da2ac9ab-b0e3-46f5-bfd0-ad350bede139",
                            Email = "jennifer.chen@onlybytes.com",
                            EmailConfirmed = false,
                            FirstName = "Jennifer",
                            JobTitleId = 3,
                            LastName = "Chen",
                            LockoutEnabled = false,
                            NormalizedEmail = "JENNIFER.CHEN@ONLYBYTES.COM",
                            NormalizedUserName = "JENNIFER.CHEN@ONLYBYTES.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c6c54f10-f90c-4993-98e8-2dab56eb0c80",
                            StationId = 4,
                            TwoFactorEnabled = false,
                            UserName = "jennifer.chen@onlybytes.com"
                        },
                        new
                        {
                            Id = "aed9019e-f2c4-4797-bcef-38c10124c27b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "84dca25b-65c4-4101-b06a-b0dc893947e0",
                            Email = "robert.taylor@onlybytes.com",
                            EmailConfirmed = false,
                            FirstName = "Robert",
                            JobTitleId = 4,
                            LastName = "Taylor",
                            LockoutEnabled = false,
                            NormalizedEmail = "ROBERT.TAYLOR@ONLYBYTES.COM",
                            NormalizedUserName = "ROBERT.TAYLOR@ONLYBYTES.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e2f11d82-7230-4a48-91d5-02ea9d4198a8",
                            StationId = 7,
                            TwoFactorEnabled = false,
                            UserName = "robert.taylor@onlybytes.com"
                        },
                        new
                        {
                            Id = "161eb0ca-8546-49af-aa84-7891c6e75f05",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8aafc2e0-df58-4710-b5d4-2eb29b7d3b55",
                            Email = "lisa.anderson@onlybytes.com",
                            EmailConfirmed = false,
                            FirstName = "Lisa",
                            JobTitleId = 4,
                            LastName = "Anderson",
                            LockoutEnabled = false,
                            NormalizedEmail = "LISA.ANDERSON@ONLYBYTES.COM",
                            NormalizedUserName = "LISA.ANDERSON@ONLYBYTES.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2adbb622-c951-4734-ae73-4eec4cb1f479",
                            StationId = 7,
                            TwoFactorEnabled = false,
                            UserName = "lisa.anderson@onlybytes.com"
                        },
                        new
                        {
                            Id = "396509bb-6fcc-43f2-8a6c-59b107b148de",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5c3f074c-ed85-4d03-afc5-de39d69427aa",
                            Email = "carlos.gomez@onlybytes.com",
                            EmailConfirmed = false,
                            FirstName = "Carlos",
                            JobTitleId = 4,
                            LastName = "Gomez",
                            LockoutEnabled = false,
                            NormalizedEmail = "CARLOS.GOMEZ@ONLYBYTES.COM",
                            NormalizedUserName = "CARLOS.GOMEZ@ONLYBYTES.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9d294c99-76ad-4f4c-8598-019e3e35cd43",
                            StationId = 7,
                            TwoFactorEnabled = false,
                            UserName = "carlos.gomez@onlybytes.com"
                        },
                        new
                        {
                            Id = "858ee96a-ffb3-4647-afe6-7dcf15bac408",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9a209f4d-947a-4b7b-9fbc-d1f0ead6c14a",
                            Email = "emma.wright@onlybytes.com",
                            EmailConfirmed = false,
                            FirstName = "Emma",
                            JobTitleId = 4,
                            LastName = "Wright",
                            LockoutEnabled = false,
                            NormalizedEmail = "EMMA.WRIGHT@ONLYBYTES.COM",
                            NormalizedUserName = "EMMA.WRIGHT@ONLYBYTES.COM",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "89e1ea2c-a5d8-4b52-8c88-1755872d5110",
                            StationId = 7,
                            TwoFactorEnabled = false,
                            UserName = "emma.wright@onlybytes.com"
                        });
                });

            modelBuilder.Entity("FastFoodAPI.Entities.JobTitle", b =>
                {
                    b.Property<int>("JobTitleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobTitleId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobTitleId");

                    b.ToTable("JobTitles");

                    b.HasData(
                        new
                        {
                            JobTitleId = 1,
                            Description = "Oversees restaurant operations and staff",
                            Title = "Manager"
                        },
                        new
                        {
                            JobTitleId = 2,
                            Description = "Handles customer transactions and orders",
                            Title = "Cashier"
                        },
                        new
                        {
                            JobTitleId = 3,
                            Description = "Prepares food according to restaurant standards",
                            Title = "Cook"
                        },
                        new
                        {
                            JobTitleId = 4,
                            Description = "Maintains cleanliness of the restaurant",
                            Title = "Cleaner"
                        });
                });

            modelBuilder.Entity("FastFoodAPI.Entities.Shift", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShiftId"));

                    b.Property<string>("ShiftPosition")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Unassigned");

                    b.HasKey("ShiftId");

                    b.ToTable("Shifts");

                    b.HasData(
                        new
                        {
                            ShiftId = 1,
                            ShiftPosition = "Day"
                        },
                        new
                        {
                            ShiftId = 2,
                            ShiftPosition = "Afternoon"
                        },
                        new
                        {
                            ShiftId = 3,
                            ShiftPosition = "Night"
                        });
                });

            modelBuilder.Entity("FastFoodAPI.Entities.ShiftAssignment", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ShiftDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EmployeeId", "ShiftId");

                    b.HasIndex("ShiftId");

                    b.ToTable("ShiftAssignments");

                    b.HasData(
                        new
                        {
                            EmployeeId = "d8be7bf6-f6ad-4835-8408-0ee470aef7a8",
                            ShiftId = 1,
                            ShiftDate = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "87dd16c6-7fe5-43e2-a378-8de5b3c8aff9",
                            ShiftId = 1,
                            ShiftDate = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "6139a95f-6ef3-4160-9cc2-45914eb759a6",
                            ShiftId = 1,
                            ShiftDate = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "11cc7b1a-09ba-48b6-a062-1b84769ed181",
                            ShiftId = 1,
                            ShiftDate = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "3a4088e6-f9f2-459a-91f3-d86d52d6ba16",
                            ShiftId = 1,
                            ShiftDate = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "858ee96a-ffb3-4647-afe6-7dcf15bac408",
                            ShiftId = 1,
                            ShiftDate = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "3052ecc5-6773-49e4-94f6-8303318375fe",
                            ShiftId = 2,
                            ShiftDate = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "6139a95f-6ef3-4160-9cc2-45914eb759a6",
                            ShiftId = 2,
                            ShiftDate = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "6cd3cd47-9274-4f6d-ac00-54e6dab140f5",
                            ShiftId = 2,
                            ShiftDate = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "3a4088e6-f9f2-459a-91f3-d86d52d6ba16",
                            ShiftId = 2,
                            ShiftDate = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "d8838fca-fee1-4a1c-b320-95262db7cd9a",
                            ShiftId = 2,
                            ShiftDate = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "aed9019e-f2c4-4797-bcef-38c10124c27b",
                            ShiftId = 2,
                            ShiftDate = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "07c4d294-fd34-4882-83c1-4e2ac1be48f7",
                            ShiftId = 3,
                            ShiftDate = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "6cd3cd47-9274-4f6d-ac00-54e6dab140f5",
                            ShiftId = 3,
                            ShiftDate = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "b27ce3ff-1b76-4c28-9368-74cee1b1c104",
                            ShiftId = 3,
                            ShiftDate = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "d8838fca-fee1-4a1c-b320-95262db7cd9a",
                            ShiftId = 3,
                            ShiftDate = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "41893200-b954-40f2-9ab8-fd11ecf243b0",
                            ShiftId = 3,
                            ShiftDate = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "161eb0ca-8546-49af-aa84-7891c6e75f05",
                            ShiftId = 3,
                            ShiftDate = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "07c4d294-fd34-4882-83c1-4e2ac1be48f7",
                            ShiftId = 1,
                            ShiftDate = new DateTime(2025, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "6cd3cd47-9274-4f6d-ac00-54e6dab140f5",
                            ShiftId = 1,
                            ShiftDate = new DateTime(2025, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "b27ce3ff-1b76-4c28-9368-74cee1b1c104",
                            ShiftId = 1,
                            ShiftDate = new DateTime(2025, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "d8838fca-fee1-4a1c-b320-95262db7cd9a",
                            ShiftId = 1,
                            ShiftDate = new DateTime(2025, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "41893200-b954-40f2-9ab8-fd11ecf243b0",
                            ShiftId = 1,
                            ShiftDate = new DateTime(2025, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "161eb0ca-8546-49af-aa84-7891c6e75f05",
                            ShiftId = 1,
                            ShiftDate = new DateTime(2025, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "ffc8c095-b46d-43d1-9976-9ea42f4a171d",
                            ShiftId = 2,
                            ShiftDate = new DateTime(2025, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "b27ce3ff-1b76-4c28-9368-74cee1b1c104",
                            ShiftId = 2,
                            ShiftDate = new DateTime(2025, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "ac8baf0a-aeb8-40c5-a8b4-632c5f692b70",
                            ShiftId = 2,
                            ShiftDate = new DateTime(2025, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "41893200-b954-40f2-9ab8-fd11ecf243b0",
                            ShiftId = 2,
                            ShiftDate = new DateTime(2025, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "fc124823-5743-41fd-aded-24a88ef1e44c",
                            ShiftId = 2,
                            ShiftDate = new DateTime(2025, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "396509bb-6fcc-43f2-8a6c-59b107b148de",
                            ShiftId = 2,
                            ShiftDate = new DateTime(2025, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "d8be7bf6-f6ad-4835-8408-0ee470aef7a8",
                            ShiftId = 3,
                            ShiftDate = new DateTime(2025, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "ac8baf0a-aeb8-40c5-a8b4-632c5f692b70",
                            ShiftId = 3,
                            ShiftDate = new DateTime(2025, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "de06c55e-1814-486a-805e-72a0d925cc13",
                            ShiftId = 3,
                            ShiftDate = new DateTime(2025, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "fc124823-5743-41fd-aded-24a88ef1e44c",
                            ShiftId = 3,
                            ShiftDate = new DateTime(2025, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "c34a7241-df42-4185-bee7-f5d1e329218c",
                            ShiftId = 3,
                            ShiftDate = new DateTime(2025, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "858ee96a-ffb3-4647-afe6-7dcf15bac408",
                            ShiftId = 3,
                            ShiftDate = new DateTime(2025, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "ac8baf0a-aeb8-40c5-a8b4-632c5f692b70",
                            ShiftId = 1,
                            ShiftDate = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "de06c55e-1814-486a-805e-72a0d925cc13",
                            ShiftId = 1,
                            ShiftDate = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "fc124823-5743-41fd-aded-24a88ef1e44c",
                            ShiftId = 1,
                            ShiftDate = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "c34a7241-df42-4185-bee7-f5d1e329218c",
                            ShiftId = 1,
                            ShiftDate = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "de06c55e-1814-486a-805e-72a0d925cc13",
                            ShiftId = 2,
                            ShiftDate = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "8efb3ddf-77b9-4f66-a6c5-08e3d0e1a4fb",
                            ShiftId = 2,
                            ShiftDate = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "c34a7241-df42-4185-bee7-f5d1e329218c",
                            ShiftId = 2,
                            ShiftDate = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "05d17d04-3c61-4d1c-8e52-f6cc7c3bf9bf",
                            ShiftId = 2,
                            ShiftDate = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "8efb3ddf-77b9-4f66-a6c5-08e3d0e1a4fb",
                            ShiftId = 3,
                            ShiftDate = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "87dd16c6-7fe5-43e2-a378-8de5b3c8aff9",
                            ShiftId = 3,
                            ShiftDate = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "05d17d04-3c61-4d1c-8e52-f6cc7c3bf9bf",
                            ShiftId = 3,
                            ShiftDate = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "11cc7b1a-09ba-48b6-a062-1b84769ed181",
                            ShiftId = 3,
                            ShiftDate = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "8efb3ddf-77b9-4f66-a6c5-08e3d0e1a4fb",
                            ShiftId = 1,
                            ShiftDate = new DateTime(2025, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "05d17d04-3c61-4d1c-8e52-f6cc7c3bf9bf",
                            ShiftId = 1,
                            ShiftDate = new DateTime(2025, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "87dd16c6-7fe5-43e2-a378-8de5b3c8aff9",
                            ShiftId = 2,
                            ShiftDate = new DateTime(2025, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "11cc7b1a-09ba-48b6-a062-1b84769ed181",
                            ShiftId = 2,
                            ShiftDate = new DateTime(2025, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "6139a95f-6ef3-4160-9cc2-45914eb759a6",
                            ShiftId = 3,
                            ShiftDate = new DateTime(2025, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "3a4088e6-f9f2-459a-91f3-d86d52d6ba16",
                            ShiftId = 3,
                            ShiftDate = new DateTime(2025, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "ffc8c095-b46d-43d1-9976-9ea42f4a171d",
                            ShiftId = 1,
                            ShiftDate = new DateTime(2025, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "396509bb-6fcc-43f2-8a6c-59b107b148de",
                            ShiftId = 1,
                            ShiftDate = new DateTime(2025, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "d8be7bf6-f6ad-4835-8408-0ee470aef7a8",
                            ShiftId = 2,
                            ShiftDate = new DateTime(2025, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "858ee96a-ffb3-4647-afe6-7dcf15bac408",
                            ShiftId = 2,
                            ShiftDate = new DateTime(2025, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "3052ecc5-6773-49e4-94f6-8303318375fe",
                            ShiftId = 3,
                            ShiftDate = new DateTime(2025, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "aed9019e-f2c4-4797-bcef-38c10124c27b",
                            ShiftId = 3,
                            ShiftDate = new DateTime(2025, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "3052ecc5-6773-49e4-94f6-8303318375fe",
                            ShiftId = 1,
                            ShiftDate = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "aed9019e-f2c4-4797-bcef-38c10124c27b",
                            ShiftId = 1,
                            ShiftDate = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "07c4d294-fd34-4882-83c1-4e2ac1be48f7",
                            ShiftId = 2,
                            ShiftDate = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "161eb0ca-8546-49af-aa84-7891c6e75f05",
                            ShiftId = 2,
                            ShiftDate = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "ffc8c095-b46d-43d1-9976-9ea42f4a171d",
                            ShiftId = 3,
                            ShiftDate = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EmployeeId = "396509bb-6fcc-43f2-8a6c-59b107b148de",
                            ShiftId = 3,
                            ShiftDate = new DateTime(2025, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("FastFoodAPI.Entities.Station", b =>
                {
                    b.Property<int>("StationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StationId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StationId");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            StationId = 1,
                            Description = "Administrative area for restaurant management",
                            IsActive = true,
                            StationName = "Management Office"
                        },
                        new
                        {
                            StationId = 2,
                            Description = "Main ordering area for customers",
                            IsActive = true,
                            StationName = "Front Counter"
                        },
                        new
                        {
                            StationId = 3,
                            Description = "Order processing for drive-thru customers",
                            IsActive = true,
                            StationName = "Drive-Thru"
                        },
                        new
                        {
                            StationId = 4,
                            Description = "Main cooking area for burgers and grilled items",
                            IsActive = true,
                            StationName = "Grill"
                        },
                        new
                        {
                            StationId = 5,
                            Description = "Station for fried food preparation",
                            IsActive = true,
                            StationName = "Fryer"
                        },
                        new
                        {
                            StationId = 6,
                            Description = "Food assembly and preparation area",
                            IsActive = true,
                            StationName = "Prep Table"
                        },
                        new
                        {
                            StationId = 7,
                            Description = "Customer seating and eating area",
                            IsActive = true,
                            StationName = "Dining Area"
                        });
                });

            modelBuilder.Entity("FastFoodAPI.Entities.Training", b =>
                {
                    b.Property<int>("TrainingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainingId"));

                    b.Property<string>("TrainingDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrainingName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrainingId");

                    b.ToTable("Trainings");

                    b.HasData(
                        new
                        {
                            TrainingId = 1,
                            TrainingDescription = "Basic food handling and safety procedures",
                            TrainingName = "Food Safety"
                        },
                        new
                        {
                            TrainingId = 2,
                            TrainingDescription = "Effective customer interaction and problem solving",
                            TrainingName = "Customer Service"
                        },
                        new
                        {
                            TrainingId = 3,
                            TrainingDescription = "Proper cash register operations and money handling",
                            TrainingName = "Cash Handling"
                        },
                        new
                        {
                            TrainingId = 4,
                            TrainingDescription = "Standard cooking methods for menu items",
                            TrainingName = "Cooking Procedures"
                        },
                        new
                        {
                            TrainingId = 5,
                            TrainingDescription = "Restaurant cleaning protocols and standards",
                            TrainingName = "Cleaning Standards"
                        });
                });

            modelBuilder.Entity("FastFoodAPI.Entities.TrainingAssignment", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TrainingId")
                        .HasColumnType("int");

                    b.Property<bool>("CompletedTraining")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("DateCompleted")
                        .HasColumnType("datetime2");

                    b.HasKey("EmployeeId", "TrainingId");

                    b.HasIndex("TrainingId");

                    b.ToTable("TrainingAssignments");

                    b.HasData(
                        new
                        {
                            EmployeeId = "3052ecc5-6773-49e4-94f6-8303318375fe",
                            TrainingId = 1,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(8988)
                        },
                        new
                        {
                            EmployeeId = "3052ecc5-6773-49e4-94f6-8303318375fe",
                            TrainingId = 2,
                            CompletedTraining = false
                        },
                        new
                        {
                            EmployeeId = "3052ecc5-6773-49e4-94f6-8303318375fe",
                            TrainingId = 3,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9860)
                        },
                        new
                        {
                            EmployeeId = "3052ecc5-6773-49e4-94f6-8303318375fe",
                            TrainingId = 4,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9871)
                        },
                        new
                        {
                            EmployeeId = "3052ecc5-6773-49e4-94f6-8303318375fe",
                            TrainingId = 5,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9874)
                        },
                        new
                        {
                            EmployeeId = "07c4d294-fd34-4882-83c1-4e2ac1be48f7",
                            TrainingId = 1,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9883)
                        },
                        new
                        {
                            EmployeeId = "07c4d294-fd34-4882-83c1-4e2ac1be48f7",
                            TrainingId = 2,
                            CompletedTraining = false
                        },
                        new
                        {
                            EmployeeId = "07c4d294-fd34-4882-83c1-4e2ac1be48f7",
                            TrainingId = 3,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9886)
                        },
                        new
                        {
                            EmployeeId = "07c4d294-fd34-4882-83c1-4e2ac1be48f7",
                            TrainingId = 4,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9888)
                        },
                        new
                        {
                            EmployeeId = "07c4d294-fd34-4882-83c1-4e2ac1be48f7",
                            TrainingId = 5,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9891)
                        },
                        new
                        {
                            EmployeeId = "ffc8c095-b46d-43d1-9976-9ea42f4a171d",
                            TrainingId = 1,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9893)
                        },
                        new
                        {
                            EmployeeId = "ffc8c095-b46d-43d1-9976-9ea42f4a171d",
                            TrainingId = 2,
                            CompletedTraining = false
                        },
                        new
                        {
                            EmployeeId = "ffc8c095-b46d-43d1-9976-9ea42f4a171d",
                            TrainingId = 3,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9895)
                        },
                        new
                        {
                            EmployeeId = "ffc8c095-b46d-43d1-9976-9ea42f4a171d",
                            TrainingId = 4,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9896)
                        },
                        new
                        {
                            EmployeeId = "ffc8c095-b46d-43d1-9976-9ea42f4a171d",
                            TrainingId = 5,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9898)
                        },
                        new
                        {
                            EmployeeId = "d8be7bf6-f6ad-4835-8408-0ee470aef7a8",
                            TrainingId = 1,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9901)
                        },
                        new
                        {
                            EmployeeId = "d8be7bf6-f6ad-4835-8408-0ee470aef7a8",
                            TrainingId = 2,
                            CompletedTraining = false
                        },
                        new
                        {
                            EmployeeId = "d8be7bf6-f6ad-4835-8408-0ee470aef7a8",
                            TrainingId = 3,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9904)
                        },
                        new
                        {
                            EmployeeId = "d8be7bf6-f6ad-4835-8408-0ee470aef7a8",
                            TrainingId = 4,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9906)
                        },
                        new
                        {
                            EmployeeId = "d8be7bf6-f6ad-4835-8408-0ee470aef7a8",
                            TrainingId = 5,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9907)
                        },
                        new
                        {
                            EmployeeId = "b27ce3ff-1b76-4c28-9368-74cee1b1c104",
                            TrainingId = 1,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9910)
                        },
                        new
                        {
                            EmployeeId = "b27ce3ff-1b76-4c28-9368-74cee1b1c104",
                            TrainingId = 2,
                            CompletedTraining = false
                        },
                        new
                        {
                            EmployeeId = "b27ce3ff-1b76-4c28-9368-74cee1b1c104",
                            TrainingId = 3,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9912)
                        },
                        new
                        {
                            EmployeeId = "ac8baf0a-aeb8-40c5-a8b4-632c5f692b70",
                            TrainingId = 1,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9915)
                        },
                        new
                        {
                            EmployeeId = "ac8baf0a-aeb8-40c5-a8b4-632c5f692b70",
                            TrainingId = 2,
                            CompletedTraining = false
                        },
                        new
                        {
                            EmployeeId = "ac8baf0a-aeb8-40c5-a8b4-632c5f692b70",
                            TrainingId = 3,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9917)
                        },
                        new
                        {
                            EmployeeId = "de06c55e-1814-486a-805e-72a0d925cc13",
                            TrainingId = 1,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9919)
                        },
                        new
                        {
                            EmployeeId = "de06c55e-1814-486a-805e-72a0d925cc13",
                            TrainingId = 2,
                            CompletedTraining = false
                        },
                        new
                        {
                            EmployeeId = "de06c55e-1814-486a-805e-72a0d925cc13",
                            TrainingId = 3,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9921)
                        },
                        new
                        {
                            EmployeeId = "8efb3ddf-77b9-4f66-a6c5-08e3d0e1a4fb",
                            TrainingId = 1,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9923)
                        },
                        new
                        {
                            EmployeeId = "8efb3ddf-77b9-4f66-a6c5-08e3d0e1a4fb",
                            TrainingId = 2,
                            CompletedTraining = false
                        },
                        new
                        {
                            EmployeeId = "8efb3ddf-77b9-4f66-a6c5-08e3d0e1a4fb",
                            TrainingId = 3,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9925)
                        },
                        new
                        {
                            EmployeeId = "87dd16c6-7fe5-43e2-a378-8de5b3c8aff9",
                            TrainingId = 1,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9927)
                        },
                        new
                        {
                            EmployeeId = "87dd16c6-7fe5-43e2-a378-8de5b3c8aff9",
                            TrainingId = 2,
                            CompletedTraining = false
                        },
                        new
                        {
                            EmployeeId = "87dd16c6-7fe5-43e2-a378-8de5b3c8aff9",
                            TrainingId = 3,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9930)
                        },
                        new
                        {
                            EmployeeId = "6139a95f-6ef3-4160-9cc2-45914eb759a6",
                            TrainingId = 1,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9932)
                        },
                        new
                        {
                            EmployeeId = "6139a95f-6ef3-4160-9cc2-45914eb759a6",
                            TrainingId = 2,
                            CompletedTraining = false
                        },
                        new
                        {
                            EmployeeId = "6139a95f-6ef3-4160-9cc2-45914eb759a6",
                            TrainingId = 3,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9934)
                        },
                        new
                        {
                            EmployeeId = "6cd3cd47-9274-4f6d-ac00-54e6dab140f5",
                            TrainingId = 1,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9937)
                        },
                        new
                        {
                            EmployeeId = "6cd3cd47-9274-4f6d-ac00-54e6dab140f5",
                            TrainingId = 2,
                            CompletedTraining = false
                        },
                        new
                        {
                            EmployeeId = "6cd3cd47-9274-4f6d-ac00-54e6dab140f5",
                            TrainingId = 3,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9939)
                        },
                        new
                        {
                            EmployeeId = "41893200-b954-40f2-9ab8-fd11ecf243b0",
                            TrainingId = 1,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9940)
                        },
                        new
                        {
                            EmployeeId = "41893200-b954-40f2-9ab8-fd11ecf243b0",
                            TrainingId = 4,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9943)
                        },
                        new
                        {
                            EmployeeId = "fc124823-5743-41fd-aded-24a88ef1e44c",
                            TrainingId = 1,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9945)
                        },
                        new
                        {
                            EmployeeId = "fc124823-5743-41fd-aded-24a88ef1e44c",
                            TrainingId = 4,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9946)
                        },
                        new
                        {
                            EmployeeId = "c34a7241-df42-4185-bee7-f5d1e329218c",
                            TrainingId = 1,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9948)
                        },
                        new
                        {
                            EmployeeId = "c34a7241-df42-4185-bee7-f5d1e329218c",
                            TrainingId = 4,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9950)
                        },
                        new
                        {
                            EmployeeId = "05d17d04-3c61-4d1c-8e52-f6cc7c3bf9bf",
                            TrainingId = 1,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9951)
                        },
                        new
                        {
                            EmployeeId = "05d17d04-3c61-4d1c-8e52-f6cc7c3bf9bf",
                            TrainingId = 4,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9953)
                        },
                        new
                        {
                            EmployeeId = "11cc7b1a-09ba-48b6-a062-1b84769ed181",
                            TrainingId = 1,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9955)
                        },
                        new
                        {
                            EmployeeId = "11cc7b1a-09ba-48b6-a062-1b84769ed181",
                            TrainingId = 4,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9956)
                        },
                        new
                        {
                            EmployeeId = "3a4088e6-f9f2-459a-91f3-d86d52d6ba16",
                            TrainingId = 1,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9958)
                        },
                        new
                        {
                            EmployeeId = "3a4088e6-f9f2-459a-91f3-d86d52d6ba16",
                            TrainingId = 4,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9960)
                        },
                        new
                        {
                            EmployeeId = "d8838fca-fee1-4a1c-b320-95262db7cd9a",
                            TrainingId = 1,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9962)
                        },
                        new
                        {
                            EmployeeId = "d8838fca-fee1-4a1c-b320-95262db7cd9a",
                            TrainingId = 4,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9963)
                        },
                        new
                        {
                            EmployeeId = "aed9019e-f2c4-4797-bcef-38c10124c27b",
                            TrainingId = 1,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9965)
                        },
                        new
                        {
                            EmployeeId = "aed9019e-f2c4-4797-bcef-38c10124c27b",
                            TrainingId = 5,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9967)
                        },
                        new
                        {
                            EmployeeId = "161eb0ca-8546-49af-aa84-7891c6e75f05",
                            TrainingId = 1,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9971)
                        },
                        new
                        {
                            EmployeeId = "161eb0ca-8546-49af-aa84-7891c6e75f05",
                            TrainingId = 5,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9972)
                        },
                        new
                        {
                            EmployeeId = "396509bb-6fcc-43f2-8a6c-59b107b148de",
                            TrainingId = 1,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9974)
                        },
                        new
                        {
                            EmployeeId = "396509bb-6fcc-43f2-8a6c-59b107b148de",
                            TrainingId = 5,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9988)
                        },
                        new
                        {
                            EmployeeId = "858ee96a-ffb3-4647-afe6-7dcf15bac408",
                            TrainingId = 1,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9990)
                        },
                        new
                        {
                            EmployeeId = "858ee96a-ffb3-4647-afe6-7dcf15bac408",
                            TrainingId = 5,
                            CompletedTraining = true,
                            DateCompleted = new DateTime(2025, 3, 13, 13, 28, 42, 359, DateTimeKind.Local).AddTicks(9991)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FastFoodAPI.Entities.Employee", b =>
                {
                    b.HasOne("FastFoodAPI.Entities.JobTitle", "JobTitle")
                        .WithMany()
                        .HasForeignKey("JobTitleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FastFoodAPI.Entities.Station", "Station")
                        .WithMany("AssignedEmployees")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("JobTitle");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("FastFoodAPI.Entities.ShiftAssignment", b =>
                {
                    b.HasOne("FastFoodAPI.Entities.Employee", "Employee")
                        .WithMany("ShiftAssignments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FastFoodAPI.Entities.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("FastFoodAPI.Entities.TrainingAssignment", b =>
                {
                    b.HasOne("FastFoodAPI.Entities.Employee", "Employee")
                        .WithMany("TrainingAssignments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FastFoodAPI.Entities.Training", "Training")
                        .WithMany("TrainingAssignments")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FastFoodAPI.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FastFoodAPI.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FastFoodAPI.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FastFoodAPI.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FastFoodAPI.Entities.Employee", b =>
                {
                    b.Navigation("ShiftAssignments");

                    b.Navigation("TrainingAssignments");
                });

            modelBuilder.Entity("FastFoodAPI.Entities.Station", b =>
                {
                    b.Navigation("AssignedEmployees");
                });

            modelBuilder.Entity("FastFoodAPI.Entities.Training", b =>
                {
                    b.Navigation("TrainingAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
