name: FastFoodApplication
on:
   push:
       branches:
           - '*'
   pull_request:
       branches:
           - '*'
   workflow_dispatch:
jobs:
   BuildAndTest:
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v4
              
          - name: Setup .NET
            uses: actions/setup-dotnet@v4
            with:
              dotnet-version: 9.0.x
          
          - name: Install Tools
            shell: bash
            run: |
              sudo apt install -y doxygen
          
          - name: Build and Run App Containers
            shell: bash
            run: docker compose up -d
          
          - name: Generate Doxygen Documentation
            shell: bash
            run: |
              doxygen Doxyfile

          - name: Upload Doxygen Documentation
            uses: actions/upload-artifact@v4
            with:
              name: documentation
              path: ./docs